runningcode/gradle-doctor

- doctor-plugin/src/main/java/com/osacky/doctor/DoctorPlugin.kt
- doctor-plugin/src/test/fixtures/dagger-jvm/build.gradle.kts
- doctor-plugin/src/test/fixtures/dagger-jvm/src/main/java/com/osacky/dagger/MyComponent.java
- doctor-plugin/src/test/fixtures/dagger-jvm/src/main/java/com/osacky/dagger/MyLibrary.java
- doctor-plugin/src/test/java/com/osacky/doctor/MultipleAndroidApps.kt
- doctor-plugin/src/test/java/com/osacky/doctor/TestDaggerTime.kt
- settings.gradle
Also add integration test for dagger annotation time in jvm.
> Fix dependency on Kotlin.

- doctor-plugin/src/main/java/com/osacky/doctor/BuildDaemonChecker.kt
- doctor-plugin/src/test/java/com/osacky/doctor/PluginIntegrationTest.kt
> Add instructions on how to disable multiple daemon check in error

- README.md
- doctor-plugin/src/main/java/com/osacky/doctor/DoctorPlugin.kt
- doctor-plugin/src/test/java/com/osacky/doctor/ProjectRootIntegrationTest.kt
- doctor-plugin/src/test/java/com/osacky/doctor/TestDaggerTime.kt
- doctor-plugin/src/test/java/com/osacky/doctor/TestFixtures.kt
- doctor-plugin/src/test/resources/non-root-fixture/build.gradle.kts
- doctor-plugin/src/test/resources/non-root-fixture/src/main/java/com/osacky/dagger/MyLibrary.java
> Ensure plugin is applied in the project root.

- .circleci/config.yml
- doctor-plugin/src/main/java/com/osacky/doctor/internal/PillBoxPrinter.kt
- doctor-plugin/src/test/java/com/osacky/doctor/internal/PillBoxPrinterTest.kt
This fixes an issue where very long lines would look really odd.
Fixes #24
> Fix line length to 80 characters.

- doctor-plugin/src/main/java/com/osacky/doctor/GarbagePrinter.kt
> Add 10 second threshold for Garbage collection warning.

- doctor-plugin/src/main/java/com/osacky/doctor/internal/PillBoxPrinter.kt
- doctor-plugin/src/test/java/com/osacky/doctor/PluginIntegrationTest.kt
- doctor-plugin/src/test/java/com/osacky/doctor/internal/PillBoxPrinterTest.kt
Also fix broken integration tests.
> More consistent pill printing.

- doctor-plugin/src/main/java/com/osacky/doctor/DoctorPlugin.kt
- doctor-plugin/src/main/java/com/osacky/doctor/JavaAnnotationTime.kt
- doctor-plugin/src/main/java/com/osacky/doctor/internal/PillBoxPrinter.kt
- doctor-plugin/src/test/java/com/osacky/doctor/PluginIntegrationTest.kt
- doctor-plugin/src/test/java/com/osacky/doctor/TestDaggerTime.kt
- doctor-plugin/src/test/java/com/osacky/doctor/internal/PillBoxPrinterTest.kt
Fixes #27
Also 100 character width for pills.
> Detect Delect on classpath to print better message.

- doctor-plugin/src/main/java/com/osacky/doctor/JavaHomeCheck.kt
> Have a better message for unset JAVA_HOME.

- doctor-plugin/src/main/java/com/osacky/doctor/BuildCacheConnectionMeasurer.kt
- doctor-plugin/src/main/java/com/osacky/doctor/DoctorExtension.kt
- doctor-plugin/src/main/java/com/osacky/doctor/DownloadSpeedMeasurer.kt
- doctor-plugin/src/main/java/com/osacky/doctor/JavaHomeCheck.kt
- doctor-plugin/src/main/java/com/osacky/doctor/internal/Decimals.kt
- doctor-plugin/src/main/java/com/osacky/doctor/internal/SlowNetworkPrinter.kt
- doctor-plugin/src/test/java/com/osacky/doctor/internal/SlowNetworkPrinterTest.kt
Fix messages around download speed.
Fix weird spacing in JAVA_HOME message.
Fixes #34.
Fixes #35.
> Better download speed default.

- doctor-plugin/src/main/java/com/osacky/doctor/BuildCacheConnectionMeasurer.kt
- doctor-plugin/src/main/java/com/osacky/doctor/DownloadSpeedMeasurer.kt
The theory is that two different threads are adding to the list at the
same time causing one spot in the list to be empty.
> Synchronize list access to prevent NPE.

- .github/workflows/gradle-wrapper-validation.yml
- build.gradle.kts
- doctor-plugin/src/test/java/com/osacky/doctor/PluginIntegrationTest.kt
- gradle/wrapper/gradle-wrapper.properties
Also add Gradle Wrapper Validation action.
> Update to Gradle 6.1.1

- doctor-plugin/src/main/java/com/osacky/doctor/DoctorPlugin.kt
- doctor-plugin/src/test/java/com/osacky/doctor/PluginIntegrationTest.kt
- doctor-plugin/src/test/resources/java-fixture/build.gradle.kts
- doctor-plugin/src/test/resources/java-fixture/src/main/java/com/osacky/dagger/MyLibrary.java
Also add test for failing on empty src directories.
> Fail on empty src directories.

- doctor-plugin/src/main/java/com/osacky/doctor/DoctorPlugin.kt
- doctor-plugin/src/test/java/com/osacky/doctor/PluginIntegrationTest.kt
It's likely not what you meant.
Fixes #20.
> Do not allow installing all apps at once.

- build.gradle.kts
- doctor-plugin/build.gradle.kts
- doctor-plugin/src/main/java/com/osacky/doctor/BuildCacheConnectionMeasurer.kt
Also don't allocate so many empty objects.
> Add test logging.

- build.gradle.kts
- doctor-plugin/src/main/java/com/osacky/doctor/DoctorPlugin.kt
- doctor-plugin/src/main/java/com/osacky/doctor/DownloadSpeedMeasurer.kt
- doctor-plugin/src/main/java/com/osacky/doctor/GarbagePrinter.kt
- doctor-plugin/src/main/java/com/osacky/doctor/internal/Clock.kt
- gradle.properties
- gradle/wrapper/gradle-wrapper.properties
- gradlew.bat
Also other minor refactorings.
> Bump Gradle to 6.2.2

- build.gradle.kts
- doctor-plugin/build.gradle.kts
- doctor-plugin/src/main/java/com/osacky/doctor/BuildOperations.kt
- doctor-plugin/src/main/java/com/osacky/doctor/RemoteCacheEstimation.kt
> Bump to kotlin 1.3.71

- doctor-plugin/src/main/java/com/osacky/doctor/RemoteCacheEstimation.kt
- gradle.properties
> Reword output report.

- README.md
- doctor-plugin/build.gradle.kts
- doctor-plugin/src/main/java/com/osacky/doctor/BuildOperations.kt
- doctor-plugin/src/main/java/com/osacky/doctor/RemoteCacheEstimation.kt
> Make code more readable.

- .circleci/config.yml
- build.gradle.kts
- dagger-kapt/build.gradle.kts
- doctor-plugin/build.gradle.kts
- doctor-plugin/src/test/java/com/osacky/doctor/PluginIntegrationTest.kt
- doctor-plugin/src/test/java/com/osacky/doctor/internal/AndroidTestUtil.kt
- gradle/wrapper/gradle-wrapper.properties
- settings.gradle
> Bump Gradle to 6.5.

- .circleci/config.yml
- build.gradle.kts
- doctor-plugin/build.gradle.kts
- doctor-plugin/src/main/java/com/osacky/doctor/BuildCacheConnectionMeasurer.kt
- doctor-plugin/src/main/java/com/osacky/doctor/BuildDaemonChecker.kt
- doctor-plugin/src/main/java/com/osacky/doctor/DoctorPlugin.kt
- doctor-plugin/src/main/java/com/osacky/doctor/DownloadSpeedMeasurer.kt
- doctor-plugin/src/main/java/com/osacky/doctor/GarbagePrinter.kt
- doctor-plugin/src/main/java/com/osacky/doctor/JavaAnnotationTime.kt
- doctor-plugin/src/main/java/com/osacky/doctor/JavaHomeCheck.kt
- doctor-plugin/src/main/java/com/osacky/doctor/OperationEvents.kt
- doctor-plugin/src/main/java/com/osacky/doctor/RemoteCacheEstimation.kt
- doctor-plugin/src/main/java/com/osacky/doctor/internal/SlowNetworkPrinter.kt
- doctor-plugin/src/test/java/com/osacky/doctor/PluginIntegrationTest.kt
- doctor-plugin/src/test/java/com/osacky/doctor/TestDaggerTime.kt
- doctor-plugin/src/test/java/com/osacky/doctor/TestFixtures.kt
- doctor-plugin/src/test/java/com/osacky/doctor/internal/PillBoxPrinterTest.kt
- doctor-plugin/src/test/java/com/osacky/doctor/internal/SlowNetworkPrinterTest.kt
- gradle/wrapper/gradle-wrapper.properties
> Bump version.

- .circleci/config.yml
- doctor-plugin/build.gradle.kts
- doctor-plugin/gradle.properties
Gradle properties are not passed to included builds https://github.com/gradle/gradle/issues/2534
> Pass Gradle Properties to included build

- CHANGELOG.md
- README.md
- doctor-plugin/src/main/java/com/osacky/doctor/RemoteCacheEstimation.kt
Allow you to control which tasks are rerun. Also adds rerunning sourcetasks and large output android tasks by default.
> Add more control over benchmarking scenarios.

- build.gradle.kts
- doctor-plugin/src/main/java/com/osacky/doctor/BuildCacheConnectionMeasurer.kt
- doctor-plugin/src/main/java/com/osacky/doctor/BuildDaemonChecker.kt
- doctor-plugin/src/main/java/com/osacky/doctor/DoctorExtension.kt
- doctor-plugin/src/main/java/com/osacky/doctor/DoctorPlugin.kt
- doctor-plugin/src/main/java/com/osacky/doctor/DownloadSpeedMeasurer.kt
- doctor-plugin/src/main/java/com/osacky/doctor/GarbagePrinter.kt
- doctor-plugin/src/main/java/com/osacky/doctor/JavaAnnotationTime.kt
- doctor-plugin/src/main/java/com/osacky/doctor/JavaHomeCheck.kt
- doctor-plugin/src/test/java/com/osacky/doctor/PluginIntegrationTest.kt
This will allow for lazy configuration and in the future configuration cache usage.
> Use Gradle Properties.

- build.gradle.kts
- doctor-plugin/build.gradle.kts
> Publish marker to maven central

- doctor-plugin/src/main/java/com/osacky/doctor/DoctorPlugin.kt
- doctor-plugin/src/main/java/com/osacky/doctor/internal/FileUtil.kt
- doctor-plugin/src/test/java/com/osacky/doctor/internal/FileUtilTest.kt
> Check for farthest empty parent for reporting file to remove

- doctor-plugin/src/main/java/com/osacky/doctor/BuildCacheConnectionMeasurer.kt
- doctor-plugin/src/main/java/com/osacky/doctor/BuildOperationListenerService.kt
- doctor-plugin/src/main/java/com/osacky/doctor/BuildOperations.kt
- doctor-plugin/src/main/java/com/osacky/doctor/DoctorPlugin.kt
- doctor-plugin/src/main/java/com/osacky/doctor/DownloadSpeedMeasurer.kt
This uses new BuildService and BuildEventListenerRegistry to listen to build events.
Ref #71
> Improve configuration caching compatibility.

- docs/changelog.md
- docs/configuration.md
- docs/index.md
- doctor-plugin/src/main/java/com/osacky/doctor/DoctorExtension.kt
- doctor-plugin/src/main/java/com/osacky/doctor/DoctorPlugin.kt
- doctor-plugin/src/main/java/com/osacky/doctor/JetifierWarning.kt
- doctor-plugin/src/test/java/com/osacky/doctor/JetifierWarningTest.kt
> Add warning when Jetifier is enabled.

- docs/changelog.md
- docs/configuration.md
- docs/index.md
- doctor-plugin/build.gradle.kts
- doctor-plugin/gradle.properties
- doctor-plugin/src/integrationTest/java/com/osacky/doctor/TestIntegrationTest.kt
- doctor-plugin/src/main/java/com/osacky/doctor/DoctorExtension.kt
- doctor-plugin/src/main/java/com/osacky/doctor/DoctorPlugin.kt
- doctor-plugin/src/main/java/com/osacky/doctor/JavaGCFlagChecker.kt
- doctor-plugin/src/parallelGCTest/java/com/osacky/doctor/ParallelGCIntegrationTest.kt
- doctor-plugin/src/test/java/com/osacky/doctor/ConfigurationCacheTest.kt
- doctor-plugin/src/test/java/com/osacky/doctor/JetifierWarningTest.kt
- doctor-plugin/src/test/java/com/osacky/doctor/PluginIntegrationTest.kt
- doctor-plugin/src/test/java/com/osacky/doctor/TestDaggerTime.kt
- doctor-plugin/src/test/java/com/osacky/doctor/internal/ScanApiTest.kt
- doctor-plugin/src/testFixtures/java/com/osacky/doctor/AbstractIntegrationTest.kt
- gradle.properties
> Recommend using parallel GC for java 9+.

- docs/changelog.md
- docs/configuration.md
- doctor-plugin/src/integrationTest/java/com/osacky/doctor/TestIntegrationTest.kt
- doctor-plugin/src/main/java/com/osacky/doctor/DoctorExtension.kt
- doctor-plugin/src/main/java/com/osacky/doctor/DoctorPlugin.kt
> Add error message for when clean task has dependencies.

- docs/configuration.md
> Groovy configuration doc update

- docs/changelog.md
- doctor-plugin/build.gradle.kts
> Fix compatibility with Java 8

- docs/changelog.md
- docs/configuration.md
- doctor-plugin/src/main/java/com/osacky/doctor/DoctorExtension.kt
- doctor-plugin/src/main/java/com/osacky/doctor/GarbagePrinter.kt
> Support fail threshold for high GC usage

- doctor-plugin/src/main/java/com/osacky/doctor/DoctorPlugin.kt
This doesn't exist anymore in Kotlin 1.7.x
Resolves #208
> Remove deleted kapt API

- docs/index.md
> Remove link to deprecated Delect project

- docs/configuration.md
- docs/index.md
- doctor-plugin/src/main/java/com/osacky/doctor/AppleRosettaTranslationCheck.kt
- doctor-plugin/src/main/java/com/osacky/doctor/DoctorExtension.kt
- doctor-plugin/src/main/java/com/osacky/doctor/DoctorPlugin.kt
- doctor-plugin/src/test/java/com/osacky/doctor/AppleRosettaTranslationCheckTest.kt
> Introduce execution modes for AppleRosettaTranslationCheck

- docs/configuration.md
> Fix indentation in configuration.md

- .gitignore
- docs/java-home.md
- doctor-plugin/src/main/java/com/osacky/doctor/internal/JavaHomeCheckPrescriptionsGenerator.kt
> Adjust java home message to also include IntelliJ

- .github/workflows/gradle-build.yml
- .github/workflows/gradle-macos-check.yml
- docs/changelog.md
- doctor-plugin/build.gradle.kts
- doctor-plugin/src/integrationTest/java/com/osacky/doctor/KotlinDaemonFallbackIntegrationTest.kt
- gradle/libs.versions.toml
This drops support for Java 8 and sets the Kotlin language version to
1.8
> Update Kotlin Language Version
