- build.gradle.kts
- doctor-plugin/src/main/java/com/osacky/doctor/DoctorExtension.kt
- doctor-plugin/src/main/java/com/osacky/doctor/DoctorPlugin.kt
- doctor-plugin/src/main/java/com/osacky/doctor/JavaHomeCheck.kt
- doctor-plugin/src/test/java/com/osacky/doctor/PluginIntegrationTest.kt
- doctor-plugin/src/test/java/com/osacky/doctor/TestDaggerTime.kt
This is better than checking if multiple daemons are running.
The multiple daemon check is now disabled by default.
> Check for java home mismatch.

- README.md
- doctor-plugin/src/main/java/com/osacky/doctor/DoctorExtension.kt
- doctor-plugin/src/main/java/com/osacky/doctor/JavaHomeCheck.kt
- doctor-plugin/src/test/java/com/osacky/doctor/PluginIntegrationTest.kt
This ensures that even if we are using sdkman to manage java versions,
we can still get the proper result.
Fixes #40.
Also enables test caching by default so as not to change default gradle
features.
Fixes #39
> Follow symlinks when checking java home.

- build.gradle.kts
- doctor-plugin/build.gradle.kts
- doctor-plugin/src/main/java/com/osacky/doctor/BuildCacheConnectionMeasurer.kt
- doctor-plugin/src/main/java/com/osacky/doctor/DoctorPlugin.kt
- doctor-plugin/src/main/java/com/osacky/doctor/DownloadSpeedMeasurer.kt
- doctor-plugin/src/main/java/com/osacky/doctor/internal/IntervalMeasurer.kt
- doctor-plugin/src/main/java/com/osacky/doctor/internal/SlowNetworkPrinter.kt
- doctor-plugin/src/test/java/com/osacky/doctor/internal/IntervalMeasurerTest.kt
- gradle.properties
Instead of adding up all the time spent downloading, we need to find the
union of all the intervals spent downloading otherwise the total
download time could be longer than the build.
> Measure time correctly for download speed.

- build.gradle.kts
- doctor-plugin/src/main/java/com/osacky/doctor/internal/SlowNetworkPrinter.kt
- doctor-plugin/src/test/java/com/osacky/doctor/internal/SlowNetworkPrinterTest.kt
- gradle/wrapper/gradle-wrapper.properties
- gradlew.bat
This previously always printed out the word "cache" even when the slow download was from maven repositories.
> Fix confusing error message with slow network.

- doctor-plugin/src/main/java/com/osacky/doctor/BuildFinishService.kt
- doctor-plugin/src/main/java/com/osacky/doctor/BuildOperations.kt
- doctor-plugin/src/main/java/com/osacky/doctor/DoctorPlugin.kt
- doctor-plugin/src/main/java/com/osacky/doctor/internal/CoCaHelpers.kt
- doctor-plugin/src/test/java/com/osacky/doctor/ConfigurationCacheTest.kt
- doctor-plugin/src/test/java/com/osacky/doctor/GradleProjects.kt
- doctor-plugin/src/test/java/com/osacky/doctor/PluginIntegrationTest.kt
This stops any configuraiton cache warnings from happening during a normal build. This does not mean that the build is fully compatibly with configuration caching or that it even works.
Ref #71
> Add initial configuration cache compatibility.

- doctor-plugin/build.gradle.kts
- doctor-plugin/src/main/java/com/osacky/doctor/BuildCacheConnectionMeasurer.kt
- doctor-plugin/src/main/java/com/osacky/doctor/BuildDaemonChecker.kt
- doctor-plugin/src/main/java/com/osacky/doctor/BuildStartFinishListener.kt
- doctor-plugin/src/main/java/com/osacky/doctor/DoctorPlugin.kt
- doctor-plugin/src/main/java/com/osacky/doctor/DownloadSpeedMeasurer.kt
- doctor-plugin/src/main/java/com/osacky/doctor/GarbagePrinter.kt
- doctor-plugin/src/main/java/com/osacky/doctor/JavaAnnotationTime.kt
- doctor-plugin/src/main/java/com/osacky/doctor/JavaHomeCheck.kt
- doctor-plugin/src/main/java/com/osacky/doctor/RemoteCacheEstimation.kt
- doctor-plugin/src/main/java/com/osacky/doctor/internal/Finish.kt
This removes the `Finish` class in favor of just returning a list of strings.
This allows a single class to return multiple warnings at the end of the build.
This also removes the direct usage of the logger from the `JavaHomeCheck`.
> Remove `Finish` and allow multiple warnings. 

- doctor-plugin/src/main/java/com/osacky/doctor/JavaHomeCheck.kt
* Fix nullability in the env var, which was null at runtime
* Don't double-pill the message when not failing on error
> Fix a couple of java home checks bugs

- docs/slower-from-cache.md
- doctor-plugin/src/main/java/com/osacky/doctor/BuildOperations.kt
- doctor-plugin/src/main/java/com/osacky/doctor/DoctorPlugin.kt
- doctor-plugin/src/main/java/com/osacky/doctor/SlowerFromCacheCollector.kt
- doctor-plugin/src/test/java/com/osacky/doctor/SlowerFromCacheCollectorTest.kt
- mkdocs.yml
When a task is pulled from the cache and takes longer to pull from the cache than the original
execution time, display a warning at the end of the build.
Ref #86
> Print tasks with negative avoidance savings.

- docs/changelog.md
- doctor-plugin/src/main/java/com/osacky/doctor/BuildOperations.kt
The race condition was causing:
`java.lang.ClassCastException: java.util.HashMap$Node cannot be cast to java.util.HashMap$TreeNode`
> Fix race condition accessing HashMap.

- doctor-plugin/src/main/java/com/osacky/doctor/JetifierWarning.kt
- doctor-plugin/src/test/java/com/osacky/doctor/JetifierWarningTest.kt
As per my [issue](https://github.com/runningcode/gradle-doctor/issues/156), this will update the console output to prescribe the correct gradle config statement to disable the jetifier. 
Updated the test to assert the console output block as it was not explicit enough to fail on my change.
> Fix typo on jetifier warning output in JetifierWarning.kt

- doctor-plugin/src/main/java/com/osacky/doctor/JavaGCFlagChecker.kt
This is the actual specification of Java that the current JDK is running for rather than using the pedantic java.version. See https://stackoverflow.com/a/5103166 for more information
Resolves #168
> Use java.specification.version for java version

- docs/remote-cache.md
Just a very minor change to remove some extra backticks from the remote cache docs that break the copy functionality when viewed from https://runningcode.github.io/gradle-doctor/remote-cache/.
> Remove extraneous backticks in docs

- build.gradle.kts
- doctor-plugin/src/main/java/com/osacky/doctor/AppleRosettaTranslationCheck.kt
- doctor-plugin/src/main/java/com/osacky/doctor/DoctorPlugin.kt
- doctor-plugin/src/main/java/com/osacky/doctor/internal/CliCommandExecutor.kt
- doctor-plugin/src/main/java/com/osacky/doctor/internal/UnixDaemonChecker.kt
- doctor-plugin/src/test/java/com/osacky/doctor/AppleRosettaTranslationCheckTest.kt
- doctor-plugin/src/test/java/com/osacky/doctor/PluginIntegrationTest.kt
- doctor-plugin/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
- gradle/wrapper/gradle-wrapper.properties
Solves: https://github.com/runningcode/gradle-doctor/issues/209
Used `sysctl.proc_translated` API via bash in order to determine if process is running under Rosetta or not according to documentation: https://developer.apple.com/documentation/apple-silicon/about-the-rosetta-translation-environment#Determine-Whether-Your-App-Is-Running-as-a-Translated-Binary
Additional related thought: maybe we need to make this check more generic and compare machine CPU architecture with running JDK target architecture? Something similar to: https://github.com/runningcode/gradle-doctor/issues/209#issuecomment-1132645634  As hardware for Windows or Linux may benefit from ARM architecture in the future as well (maybe already there is some variants in the market).
> Implement Apple Rosetta translation check

- doctor-plugin/src/main/java/com/osacky/doctor/JavaHomeCheck.kt
Fixes #187 
We can take it further and resolve and compare other known java dirs ie `lib`, `jre`. However I believe `bin` is sufficient since this feature mostly cares about build reproducibility.
Sadly I don't know a good way to test it since this feature is completely environment dependent, I'm happy to add such tests if anybody have an idea how to do it though.
> Compare bin subdirs of java home on root mismatch [fix 187]

- doctor-plugin/src/main/java/com/osacky/doctor/JavaHomeCheck.kt
Reverts runningcode/gradle-doctor#240
This doesn't work. I have this issue on my local machine:
```
| Gradle is not using JAVA_HOME.                                                                       |
| JAVA_HOME is /Users/no/.asdf/installs/java/adoptopenjdk-11.0.11+9                                    |
| Gradle is using /Users/no/.asdf/installs/java/adoptopenjdk-11.0.11+9                                 |
| This can slow down your build significantly when switching from Android Studio to the terminal.      |
| To fix: Project Structure -> JDK Location.                                                           |
| Set this to your JAVA_HOME.
```
See build scan here: https://scans.gradle.com/s/utvdqanc3oila
> Revert "Compare bin subdirs of java home on root mismatch [fix 187]"

- docs/slower-from-cache.md
The groovy and kotlin examples where inverted
> fix: correct inverted syntax

- .github/workflows/gradle-macos-check.yml
- doctor-plugin/src/main/java/com/osacky/doctor/AppleRosettaTranslationCheck.kt
- doctor-plugin/src/main/java/com/osacky/doctor/internal/CliCommandExecutor.kt
- doctor-plugin/src/test/java/com/osacky/doctor/AppleRosettaTranslationCheckTest.kt
When running the Apple Rosetta check on an Intel MacOS machine, the sysctl command exists with non-success result value.
That case is correctly handled in the check logic but breaks Gradle configuration cache as the command output is an Exception.
It should be enough to ignore the exit value of the process to restore the configuration cache usage.
> fix: Ignore process exit value for Apple Rosetta check

- .github/workflows/gradle-dependency-submission.yml
- build.gradle.kts
- gradle/libs.versions.toml
- Adds dependency graph workflow using `gradle/actions/dependency-submission`.
- Fixes a reported vulnerability by upgrading transitive dependency in plugin classpath.
> Add dependency submission workflow (and fix a vulnerability)

- .github/workflows/gradle-build.yml
- .github/workflows/gradle-macos-check.yml
- build.gradle.kts
- doctor-plugin/src/main/java/com/osacky/doctor/DoctorPlugin.kt
- doctor-plugin/src/main/java/com/osacky/doctor/JavaHomeCheck.kt
- doctor-plugin/src/main/java/com/osacky/doctor/internal/JavaHomeCheckPrescriptionsGenerator.kt
- doctor-plugin/src/test/java/com/osacky/doctor/JavaHomeCheckTest.kt
- doctor-plugin/src/test/java/com/osacky/doctor/internal/SpyJavaHomePrescriptionsGenerator.kt
Motivation for change - see this [thread](https://github.com/runningcode/gradle-doctor/pull/241#issuecomment-1987283775).
Changes:
- java home check now looks for or tries to resolve **bin** folder(where all executables [reside](https://docs.oracle.com/javase/8/docs/technotes/tools/windows/jdkfiles.html) by default) in order to resolve full/real path. It still has a fallback to initial path in case **bin** isn't there
- added `JvmVariables` and `JavaHomeCheckConfig` in order to use them as "injectable" `JavaHomeCheck` constructor params, which slightly improves testability and decoupling. 
- added `JavaHomeCheckPrescriptionsGenerator` and it's default implementation. Same reasoning - better testability and decoupling(nice to have a dedicated abstraction just to delegate the exact message …
> Added support for zulu like jdks by performing the java home check based on bin(executables folder).

- doctor-plugin/src/main/java/com/osacky/doctor/DoctorPlugin.kt
`appleRosettaTranslationCheckMode` is always `ERROR`, because the check runs before the extension is configured.
> Fix run apple rosetta translation check

- docs/scan-tags.md
Update remaining uses of "Gradle Enterprise" to Develocity. Link "Develocity" to the Develocity home page instead of the plugin manual.
> Update mentions of Develocity

- doctor-plugin/src/main/java/com/osacky/doctor/JavaHomeCheck.kt
- doctor-plugin/src/test/java/com/osacky/doctor/JavaHomeCheckTest.kt
All the context is in #436
close #436
`.get()` never returns `null`. And I see that all the logic on this rule works with that assumption. For that reason I changed it to `.getOrNull()`.
> Don't crash when `JAVA_HOME` is not set
